In [2]:
import numpy as np

Lx, Ly, Lz =10, 10, 10
epsilon =1.
sigma = 1.

#转算坐标到reference box
def wrap(r,Lx,Ly,Lz):
    wrapped_r = np.array([r[0]%Lx,r[1]%Ly,r[2]%Lz])
    return wrapped_r

#minimum image distance
def MI_distance(r1,r2,Lx,Ly,Lz):
    delta = r1-r2
    #print(delta)
    #归一化到(-L/2, L/2]范围
    delta[0] -=np.round(delta[0]/Lx)*Lx
    delta[1] -=np.round(delta[1]/Ly)*Ly
    delta[2] -=np.round(delta[2]/Lz)*Lz
    #print(delta)
    distance = np.sqrt(np.sum(delta**2))
    return distance

def LJ(r,epsilon ,sigma):
    return 4*epsilon*((sigma/r)**12-(sigma/r)**6)

particles = [(np.array([1, 1, 1]), np.array([2, 2, 2])),(np.array([1, 1, 1]), np.array([1, 1, 9])),(np.array([1, 1, 1]), np.array([9, 9, 9]))]

for a, b in particles:
    new_a = wrap(a,Lx,Ly,Lz)
    new_b = wrap(b,Lx,Ly,Lz)
    distance = MI_distance(a,b,Lx,Ly,Lz)
    lj = LJ(distance,epsilon,sigma)
    print(f"{a}—>{new_a}")
    print(f"{b}—>{new_b}")
    print(f"Minimum image distance = {distance}")
    print(f"Lennard-Jones Potential = {lj}\n")
    


[1 1 1]—>[1 1 1]
[2 2 2]—>[2 2 2]
Minimum image distance = 1.7320508075688772
Lennard-Jones Potential = -0.14266117969821684

[1 1 1]—>[1 1 1]
[1 1 9]—>[1 1 9]
Minimum image distance = 2.0
Lennard-Jones Potential = -0.0615234375

[1 1 1]—>[1 1 1]
[9 9 9]—>[9 9 9]
Minimum image distance = 3.4641016151377544
Lennard-Jones Potential = -0.0023134752229080954

